# Poppy Universe – Layer 3: Planet Matrix Model

Welcome to the **Poppy Universe Layer 3 – Planet Matrix notebook**!  
The planet dataset is already fully correct. Here, we focus on **building a matrix-based recommendation model** using simulated user interactions and planet types. This is a **sandbox environment** to test collaborative filtering before the engine consumes it.

> Note: This notebook currently uses **simulated user interactions** to test the Planet matrix.  
> Once we have enough real interactions, the same pipeline will process actual user data for production recommendations.

---

## Goals

1. **Prepare interaction data for matrix factorization**  
   - Map users to planet types  
   - Include weighted interactions (views, clicks, favorites, ratings)  
   - Normalize scores for ML input

2. **Build the User × Planet_Type matrix**  
   - Users in rows, planet types in columns  
   - Populate with interaction strengths  

3. **Perform matrix factorization / prediction**  
   - Generate predicted scores for each user × planet_type  
   - Save intermediate CSV for engine integration

4. **Analyze results**  
   - Identify top planet types per user  
   - Visualize patterns across users and planet types

---

## Folder & File References

- **../../Input_Data/Planets.csv** → Planet dataset  
- **../../Input_Data/Semantic_Type_Interactions.csv** → User interaction dataset  
- **../../Output_Data/Layer3_Planet_Predictions.csv** → Final predictions for engine  
- **Plots/** → Optional heatmaps or visualizations

---

> Note: This notebook focuses **on the planet component** of Layer 3. Stars and moons will have separate notebooks, then merged later.


## 0) Imports

In [1]:
import pandas as pd
import numpy as np
import os
from datetime import datetime, timedelta

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import TruncatedSVD

## 1) Load Data

In [3]:
# --- Load interaction dataset ---
# 'backend_df' is injected via papermill by the master notebook if backend data passed the checks
try:
    interactions = backend_df
    print("Using backend-provided interactions")
except NameError:
    # fallback to CSV if running standalone
    interactions = pd.read_csv("../../../Input_Data/MF_Semantic_Type_Interactions.csv")
    print("Using simulated CSV interactions")

# Ensure Timestamp is datetime
interactions['Timestamp'] = pd.to_datetime(interactions['Timestamp'])

# Preview
interactions.head()

Using simulated CSV interactions


Interaction_ID  User_ID Category_Type Category_Value  Strength  \
0               1       86          Star              K         4   
1               2       50        Planet    Terrestrial         1   
2               3       96        Planet   Dwarf Planet         1   
3               4       54        Planet      Ice Giant         3   
4               5       22        Planet      Ice Giant         5   

                   Timestamp  
0 2025-12-05 18:42:31.865100  
1 2025-11-28 04:57:19.070873  
2 2025-12-04 01:06:16.214604  
3 2025-11-20 07:14:48.239208  
4 2025-11-14 01:40:03.455302

**Explanation:**  
We’re loading the simulated user × type interaction data to see what we have. The key columns are:
 
- `Interaction_ID`: unique identifier for each interaction  
- `User_ID`: the user who performed the interaction  
- `Category_Type`: the type of category the interaction belongs to (e.g., Star_Type, Planet_Type, Moon_Parent)  
- `Category_Value`: the specific value within the category (e.g., G for Star_Type, Dwarf Planet for Planet_Type)  
- `Strength`: numerical interaction strength (1–5), used as a matrix factorization target  
- `Timestamp`: when the interaction occurred  
 
This gives us the base data we’ll use to compute features like user-type preferences, recency-weighted strengths, and the semantic matrices for the third layer of the recommendation engine.

## 2) Filter out Star and moon data

In [5]:
# Keep only rows where Category_Type is "Planet"
planet_interactions = interactions[interactions['Category_Type'] == 'Planet']

planet_interactions.head()

Interaction_ID  User_ID Category_Type Category_Value  Strength  \
1               2       50        Planet    Terrestrial         1   
2               3       96        Planet   Dwarf Planet         1   
3               4       54        Planet      Ice Giant         3   
4               5       22        Planet      Ice Giant         5   
5               6       35        Planet      Ice Giant         2   

                   Timestamp  
1 2025-11-28 04:57:19.070873  
2 2025-12-04 01:06:16.214604  
3 2025-11-20 07:14:48.239208  
4 2025-11-14 01:40:03.455302  
5 2025-12-01 04:21:19.584502

## 3) Create User × Category Matrix

In [6]:
# Pivot: rows = users, cols = category values, values = max strength (or sum/mean if multiple)
user_category_matrix = planet_interactions.pivot_table(
    index='User_ID', 
    columns='Category_Value', 
    values='Strength', 
    aggfunc='max',   # could also be sum or mean
    fill_value=0     # fills missing interactions with 0
)

# Optional: reset column names if you want a flat DataFrame
user_category_matrix = user_category_matrix.reset_index()

print(user_category_matrix.head())


Category_Value  User_ID  Dwarf Planet  Gas Giant  Ice Giant  Terrestrial
0                     1             5          4          5            5
1                     2             4          5          5            5
2                     3             5          5          5            5
3                     4             4          5          5            5
4                     5             5          5          4            5


## 4) Matrix Factorization with SGD

In [7]:
# Convert pivot table to numpy array (exclude User_ID column)
R = user_category_matrix.drop('User_ID', axis=1).values
num_users, num_items = R.shape
K = 3  # number of latent features

# Initialize user and item latent matrices randomly
np.random.seed(42)
U = np.random.rand(num_users, K)  # Users × Features
V = np.random.rand(num_items, K)  # Items × Features

# Hyperparameters
alpha = 0.01   # learning rate
beta = 0.02    # regularization term
iterations = 1000

# SGD loop
for it in range(iterations):
    for i in range(num_users):
        for j in range(num_items):
            if R[i, j] > 0:  # only consider observed interactions
                # Predict
                pred = U[i, :].dot(V[j, :].T)
                # Error
                e_ij = R[i, j] - pred
                # Update latent features
                U[i, :] += alpha * (2 * e_ij * V[j, :] - beta * U[i, :])
                V[j, :] += alpha * (2 * e_ij * U[i, :] - beta * V[j, :])

# Reconstruct approximate matrix
R_hat = U.dot(V.T)

print("Original matrix:\n", R)
print("Approximated matrix:\n", R_hat)

Original matrix:
 [[5 4 5 5]
 [4 5 5 5]
 [5 5 5 5]
 [4 5 5 5]
 [5 5 4 5]
 [4 5 5 3]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 0 4]
 [3 3 4 4]
 [5 5 4 5]
 [4 5 5 5]
 [4 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 4]
 [5 5 5 4]
 [5 5 2 5]
 [5 5 5 5]
 [5 4 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [4 4 1 5]
 [5 5 4 4]
 [5 5 5 5]
 [5 4 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [4 4 4 5]
 [4 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 3 4 5]
 [5 4 5 4]
 [4 5 5 5]
 [5 4 5 4]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 4 5]
 [5 5 5 5]
 [5 4 5 5]
 [5 5 5 4]
 [4 5 5 5]
 [5 5 5 5]
 [4 5 4 5]
 [5 5 5 5]
 [5 3 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 4 4 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 4]
 [5 4 5 5]
 [4 4 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 4 4]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 4 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 0 5]
 [5 5 5 4]
 [5 5 4 5]
 [3 3 5 5]
 [5 5 5 4]
 [4

## 5) Convert Approximated Matrix Back to DataFrame

In [8]:
# Convert R_hat back to DataFrame
R_hat_df = pd.DataFrame(R_hat, columns=user_category_matrix.columns[1:])  # skip User_ID
R_hat_df['User_ID'] = user_category_matrix['User_ID'].values

# Optional: reorder columns so User_ID is first
cols = ['User_ID'] + [c for c in R_hat_df.columns if c != 'User_ID']
R_hat_df = R_hat_df[cols]

R_hat_df.head()


Category_Value  User_ID  Dwarf Planet  Gas Giant  Ice Giant  Terrestrial
0                     1      4.710570   4.136557   5.032102     5.042292
1                     2      4.860355   4.620260   4.830528     4.785199
2                     3      5.107094   4.934059   4.965450     4.959903
3                     4      4.859762   4.616647   4.832396     4.788828
4                     5      4.926277   4.989948   4.015977     4.988191

## 6) Save Predicted Matrix to CSV

In [9]:
# Save as CSV for master notebook
R_hat_df.to_csv('../Files/Layer3_Planet_Predictions.csv', index=False)

# Optional: preview
print(R_hat_df.head())

Category_Value  User_ID  Dwarf Planet  Gas Giant  Ice Giant  Terrestrial
0                     1      4.710570   4.136557   5.032102     5.042292
1                     2      4.860355   4.620260   4.830528     4.785199
2                     3      5.107094   4.934059   4.965450     4.959903
3                     4      4.859762   4.616647   4.832396     4.788828
4                     5      4.926277   4.989948   4.015977     4.988191
